"""Seed data for chrisamaya.work pSEO tenant (v4)."""

DEFAULT_THEME = {
    "palette": "emerald",
    "cdn_provider": "cloudflare",
    "cdn_config": {},  # Optional: { "zone_id": "...", "api_token": "..." } or use CLOUDFLARE_* env vars
    "site_name": "Chris Amaya",
    "content_structure": {
        "section_ids": {
            "hero": "hero",
            "about": "about",
            "services": "services",
            "faq": "faq",
            "contact": "contact",
            "calculator": "calculator",
            "survey": "survey",
        }
    },
    "scripts": ["scroll-progress", "particles", "animation-observer"],
    "nav": {
        "portfolio": [
            {"name": "About Me", "href": "/#about"},
            {"name": "Projects", "href": "/#projects"},
            {"name": "Blog", "href": "/blog"},
            {"name": "How I Build", "href": "/guide/how-i-build"},
            {"name": "Knowledge Base", "href": "/knowledge-base"},
            {"name": "Search", "href": "/search"},
            {"name": "Contact", "href": "/#contact"},
        ],
        "custom_apps": [
            {"name": "Python & FastAPI", "href": "/services/custom-apps/python-api"},
            {"name": "Astro & React", "href": "/services/custom-apps/frontend"},
            {"name": "Full-Stack", "href": "/services/custom-apps/full-stack"},
            {"name": "PostgreSQL", "href": "/services/custom-apps/database"},
            {"name": "Google APIs", "href": "/services/custom-apps/google-apis"},
            {"name": "WordPress", "href": "/services/custom-apps/wordpress"},
            {"name": "Calculators", "href": "/services/custom-apps/calculators"},
            {"name": "3D & Visual", "href": "/services/custom-apps/3d-visual"},
        ],
        "growth_tools": [],
        "cta": {"label": "Work With Me", "href": "#contact"},
    },
    "footer": {
        "tagline": "The Unicorn Developer.",
        "copyright": "Chris Amaya",
    },
}

LOCATIONS = [
    {"city": "Austin", "state": "TX", "zip": "73301", "slug": "austin-tx"},
    {"city": "Dallas", "state": "TX", "zip": "75201", "slug": "dallas-tx"},
    {"city": "Houston", "state": "TX", "zip": "77001", "slug": "houston-tx"},
    {"city": "San Antonio", "state": "TX", "zip": "78201", "slug": "san-antonio-tx"},
    {"city": "Fort Worth", "state": "TX", "zip": "76101", "slug": "fort-worth-tx"},
    {"city": "Miami", "state": "FL", "zip": "33101", "slug": "miami-fl"},
    {"city": "Orlando", "state": "FL", "zip": "32801", "slug": "orlando-fl"},
    {"city": "Tampa", "state": "FL", "zip": "33601", "slug": "tampa-fl"},
    {"city": "Jacksonville", "state": "FL", "zip": "32201", "slug": "jacksonville-fl"},
    {"city": "Atlanta", "state": "GA", "zip": "30301", "slug": "atlanta-ga"},
    {"city": "Phoenix", "state": "AZ", "zip": "85001", "slug": "phoenix-az"},
    {"city": "Denver", "state": "CO", "zip": "80201", "slug": "denver-co"},
    {"city": "Las Vegas", "state": "NV", "zip": "89101", "slug": "las-vegas-nv"},
    {"city": "Charlotte", "state": "NC", "zip": "28201", "slug": "charlotte-nc"},
    {"city": "Raleigh", "state": "NC", "zip": "27601", "slug": "raleigh-nc"},
    {"city": "Nashville", "state": "TN", "zip": "37201", "slug": "nashville-tn"},
    {"city": "Chicago", "state": "IL", "zip": "60601", "slug": "chicago-il"},
    {"city": "Seattle", "state": "WA", "zip": "98101", "slug": "seattle-wa"},
    {"city": "Portland", "state": "OR", "zip": "97201", "slug": "portland-or"},
    {"city": "San Diego", "state": "CA", "zip": "92101", "slug": "san-diego-ca"},
    {"city": "Los Angeles", "state": "CA", "zip": "90001", "slug": "los-angeles-ca"},
    {"city": "San Francisco", "state": "CA", "zip": "94101", "slug": "san-francisco-ca"},
    {"city": "San Jose", "state": "CA", "zip": "95101", "slug": "san-jose-ca"},
    {"city": "Columbus", "state": "OH", "zip": "43201", "slug": "columbus-oh"},
    {"city": "Indianapolis", "state": "IN", "zip": "46201", "slug": "indianapolis-in"},
    {"city": "Minneapolis", "state": "MN", "zip": "55401", "slug": "minneapolis-mn"},
    {"city": "Detroit", "state": "MI", "zip": "48201", "slug": "detroit-mi"},
    {"city": "Philadelphia", "state": "PA", "zip": "19101", "slug": "philadelphia-pa"},
    {"city": "Boston", "state": "MA", "zip": "02101", "slug": "boston-ma"},
    {"city": "New York", "state": "NY", "zip": "10001", "slug": "new-york-ny"},
    {"city": "Washington", "state": "DC", "zip": "20001", "slug": "washington-dc"},
    {"city": "Baltimore", "state": "MD", "zip": "21201", "slug": "baltimore-md"},
    {"city": "Richmond", "state": "VA", "zip": "23219", "slug": "richmond-va"},
    {"city": "Salt Lake City", "state": "UT", "zip": "84101", "slug": "salt-lake-city-ut"},
    {"city": "Kansas City", "state": "MO", "zip": "64101", "slug": "kansas-city-mo"},
    {"city": "St. Louis", "state": "MO", "zip": "63101", "slug": "st-louis-mo"},
    {"city": "Milwaukee", "state": "WI", "zip": "53201", "slug": "milwaukee-wi"},
    {"city": "Cleveland", "state": "OH", "zip": "44101", "slug": "cleveland-oh"},
    {"city": "Cincinnati", "state": "OH", "zip": "45201", "slug": "cincinnati-oh"},
    {"city": "Pittsburgh", "state": "PA", "zip": "15201", "slug": "pittsburgh-pa"},
    {"city": "Raleigh-Durham", "state": "NC", "zip": "27601", "slug": "raleigh-durham-nc"},
    {"city": "Austin-Round Rock", "state": "TX", "zip": "78701", "slug": "austin-round-rock-tx"},
    {"city": "Boulder", "state": "CO", "zip": "80301", "slug": "boulder-co"},
    {"city": "Ann Arbor", "state": "MI", "zip": "48103", "slug": "ann-arbor-mi"},
    {"city": "Durham", "state": "NC", "zip": "27701", "slug": "durham-nc"},
    {"city": "Madison", "state": "WI", "zip": "53701", "slug": "madison-wi"},
    {"city": "Omaha", "state": "NE", "zip": "68101", "slug": "omaha-ne"},
    {"city": "Des Moines", "state": "IA", "zip": "50301", "slug": "des-moines-ia"},
    {"city": "Boise", "state": "ID", "zip": "83701", "slug": "boise-id"},
    {"city": "Albuquerque", "state": "NM", "zip": "87101", "slug": "albuquerque-nm"},
]

PSEO_SERVICES = [
    {"service_type": "Custom SaaS", "sub_niche": "Development", "slug": "custom-saas-development"},
    {"service_type": "Private AI", "sub_niche": "Automation System", "slug": "private-ai-automation-system"},
    {"service_type": "Zapier", "sub_niche": "Replacement Workflow", "slug": "zapier-replacement-workflow"},
    {"service_type": "Headless", "sub_niche": "CMS Architecture", "slug": "headless-cms-architecture"},
    {"service_type": "Programmatic SEO", "sub_niche": "Engine", "slug": "programmatic-seo-engine"},
    {"service_type": "Full-Stack", "sub_niche": "Unicorn App", "slug": "full-stack-unicorn-app"},
    {"service_type": "AI-Powered", "sub_niche": "Business Automation", "slug": "ai-powered-business-automation"},
    {"service_type": "Headless", "sub_niche": "E-commerce", "slug": "headless-ecommerce"},
    {"service_type": "API-First", "sub_niche": "Backend", "slug": "api-first-backend"},
    {"service_type": "Serverless", "sub_niche": "Infrastructure", "slug": "serverless-infrastructure"},
    {"service_type": "Edge", "sub_niche": "Rendering", "slug": "edge-rendering"},
    {"service_type": "AI Agents", "sub_niche": "Integration", "slug": "ai-agents-integration"},
    {"service_type": "Data Pipeline", "sub_niche": "Automation", "slug": "data-pipeline-automation"},
    {"service_type": "Revenue Engine", "sub_niche": "SaaS", "slug": "revenue-engine-saas"},
    {"service_type": "Private AI", "sub_niche": "System Build", "slug": "private-ai-system-build"},
    {"service_type": "Zapier", "sub_niche": "Native Replacement", "slug": "zapier-native-replacement"},
    {"service_type": "Custom Dashboard", "sub_niche": "B2B", "slug": "custom-dashboard-b2b"},
    {"service_type": "Integrations", "sub_niche": "Hub", "slug": "integrations-hub"},
    {"service_type": "Workflow", "sub_niche": "Orchestration", "slug": "workflow-orchestration"},
    {"service_type": "CRM", "sub_niche": "Transformation", "slug": "crm-transformation"},
    {"service_type": "Funnel", "sub_niche": "Architecture", "slug": "funnel-architecture"},
    {"service_type": "Paid", "sub_niche": "Acquisition", "slug": "paid-acquisition"},
    {"service_type": "Growth", "sub_niche": "Retainer", "slug": "growth-retainer"},
    {"service_type": "Authority", "sub_niche": "Engine", "slug": "authority-engine"},
    {"service_type": "Data", "sub_niche": "Attribution", "slug": "data-attribution"},
    {"service_type": "Unicorn", "sub_niche": "Developer Day", "slug": "unicorn-developer-day"},
    {"service_type": "AI", "sub_niche": "Architecture Audit", "slug": "ai-architecture-audit"},
    {"service_type": "Technical", "sub_niche": "Strategy Session", "slug": "technical-strategy-session"},
    {"service_type": "Programmatic", "sub_niche": "Content Factory", "slug": "programmatic-content-factory"},
    {"service_type": "Headless", "sub_niche": "Migration", "slug": "headless-migration"},
    {"service_type": "Automation", "sub_niche": "Blueprint", "slug": "automation-blueprint"},
    {"service_type": "AI Readiness", "sub_niche": "Assessment", "slug": "ai-readiness-assessment"},
    {"service_type": "Revenue", "sub_niche": "Pipeline Build", "slug": "revenue-pipeline-build"},
    {"service_type": "Custom Integrations", "sub_niche": "Development", "slug": "custom-integrations-development"},
    {"service_type": "MVP", "sub_niche": "Development", "slug": "mvp-development"},
    {"service_type": "Scale-Up", "sub_niche": "Architecture", "slug": "scale-up-architecture"},
]

SYNONYM_GROUPS = [
    {"category": "grow", "terms": ["scale", "explode", "multiply", "skyrocket", "accelerate", "supercharge", "dominate", "10x", "elevate", "optimize", "amplify", "revolutionize", "transform", "catapult", "turbocharge", "ignite", "propel", "hypergrow", "thrive", "flourish"]},
    {"category": "unicorn", "terms": ["one-stop architect", "unicorn developer", "full-stack genius", "AI-native builder", "automation god", "private AI engineer", "headless wizard", "SaaS visionary", "Zapier slayer", "programmatic master", "revenue architect", "AI systems builder", "custom SaaS creator", "enterprise automation hero", "10x developer"]},
    {"category": "software", "terms": ["SaaS platform", "web application", "digital product", "custom software", "tech stack", "web architecture", "cloud solution", "enterprise system", "private AI system", "headless CMS", "automation engine", "revenue machine", "business OS", "AI workflow", "custom dashboard"]},
    {"category": "expert", "terms": ["elite", "specialized", "top-tier", "veteran", "industry-leading", "proven", "dedicated", "highly-skilled", "premier", "world-class", "battle-tested", "hand-selected", "certified", "renowned", "trusted"]},
    {"category": "fast", "terms": ["rapidly", "quickly", "efficiently", "in record time", "without delay", "predictably", "seamlessly", "instantly", "blazing fast", "lightning speed", "under 14 days", "overnight", "in hours", "zero downtime"]},
    {"category": "leads", "terms": ["qualified leads", "high-intent prospects", "inbound pipeline", "revenue opportunities", "targeted traffic", "ideal customers", "paying clients", "enterprise deals", "warm prospects", "high-value inquiries", "booked calls", "signed contracts"]},
    {"category": "revenue", "terms": ["ARR", "bottom line", "profit margins", "sales volume", "top-line growth", "MRR", "recurring revenue", "cash flow", "lifetime value", "pipeline value", "monthly recurring", "enterprise revenue"]},
    {"category": "audit", "terms": ["technical review", "deep-dive analysis", "structural breakdown", "performance evaluation", "comprehensive assessment", "full-stack audit", "AI readiness check", "Zapier replacement scan", "headless migration review"]},
    {"category": "architecture", "terms": ["system architecture", "tech stack design", "infrastructure blueprint", "scalable foundation", "enterprise-grade build", "AI-native design", "headless framework", "private cloud setup", "automation backbone"]},
    {"category": "ai", "terms": ["private AI", "custom AI", "AI automation", "intelligent system", "machine learning layer", "generative AI", "AI agent", "AI workflow", "neural engine", "autonomous AI", "AI copilot"]},
    {"category": "automation", "terms": ["zero-touch automation", "end-to-end workflow", "smart automation", "AI-driven process", "no-code replacement", "Zapier killer", "hands-free system", "orchestration layer", "intelligent routing", "self-healing pipeline"]},
    {"category": "pipeline", "terms": ["sales pipeline", "lead pipeline", "revenue pipeline", "inbound engine", "conversion funnel", "customer journey", "deal flow", "opportunity stream", "growth engine"]},
    {"category": "convert", "terms": ["turn into clients", "close deals", "book calls", "generate revenue", "drive signups", "boost conversions", "monetize traffic", "maximize ROI", "capture enterprise"]},
    {"category": "headless", "terms": ["headless CMS", "edge-rendered frontend", "decoupled architecture", "Jamstack build", "Astro/Next.js stack", "API-first system", "content mesh", "serverless frontend"]},
    {"category": "programmatic", "terms": ["programmatic SEO", "dynamic content engine", "auto-generated pages", "scale-ready matrix", "location × service factory", "massive slug routing", "AI content layer"]},
    {"category": "zapier", "terms": ["Zapier replacement", "native automation", "custom workflow engine", "enterprise-grade integration", "zero-third-party dependency", "private automation layer"]},
    {"category": "results", "terms": ["10x growth", "187k saved", "3.4x pipeline", "98% uptime", "14-day delivery", "zero maintenance", "full ROI in 37 days"]},
    {"category": "survey", "terms": ["Unicorn Readiness Survey", "AI Architecture Audit", "Zapier Replacement Scorecard", "Private AI Blueprint", "Headless Readiness Check"]},
    {"category": "cta", "terms": ["Book your slot", "Start survey now", "Claim free audit", "Reserve Unicorn Day", "Get instant roadmap"]},
    {"category": "tech_stack", "terms": ["Next.js + Astro", "Supabase + Edge", "AI agents + LangChain", "Headless + Tailwind", "Custom SaaS stack"]},
    {"category": "local", "terms": ["{City} tech scene", "{County} enterprises", "near {Landmark}", "{State} startups"]},
]

SPINTAX = [
    {"category": "b2b_pain_points", "data": ["Tired of being your own CTO?", "Still glued to Zapier every Monday?", "Spending $15k/month on devs who miss deadlines?", "Manual workflows eating 20 hours/week?", "Legacy systems killing your growth?", "Third-party tools failing at scale?", "AI hype without real results?", "Pipeline drying up month after month?", "Competitors outranking you daily?", "Custom code breaking every update?", "Integration hell slowing your team?", "No visibility into true ROI?"]},
    {"category": "tech_value_props", "data": ["We engineer private AI systems that run while you sleep.", "Our headless architecture delivers perfect Core Web Vitals.", "Programmatic SEO turns your domain into a 24/7 lead magnet.", "Zapier replacements built in native code for zero latency.", "Full-stack unicorn builds delivered in under 14 days.", "AI agents that replace entire departments.", "Revenue engines that scale to 10,000 concurrent users."]},
    {"category": "urgency_hooks", "data": ["The digital landscape is shifting fast.", "Your competitors aren't waiting.", "Every day without automation costs thousands.", "Search algorithms reward speed and scale.", "AI adoption gap is widening daily."]},
    {"category": "social_proof", "data": ["Trusted by fast-growing startups.", "Empowering B2B teams to own their tech destiny.", "Recognized for delivering measurable pipeline growth.", "Proven track record of 10x revenue in under 90 days."]},
    {"category": "geo_brags", "data": ["Serving top tech companies near the landmark.", "Premier unicorn developer for county businesses.", "Based right here — we live the local market.", "Proudly building for the state innovation ecosystem."]},
    {"category": "results_quantified", "data": ["Saved Austin fintech $187k/yr on automation.", "Delivered 3.4x pipeline growth in 47 days.", "98% uptime for enterprise clients.", "14-day average delivery for custom SaaS."]},
    {"category": "survey_hooks", "data": ["Take the 90-second Unicorn Readiness Survey.", "Get your free Private AI Architecture Blueprint.", "Score your Zapier replacement potential instantly."]},
    {"category": "objection_handlers", "data": ["Already have a dev team? Here's why you still need a unicorn.", "Budget concerns? See the ROI calculator below.", "Not ready for AI? Start with a 2-hour audit."]},
    {"category": "faq_answers", "data": ["Usually 14 days for production-grade replacement.", "We guarantee 82% uniqueness across all pages.", "Leads hit your inbox within 3 seconds."]},
    {"category": "cta_strong", "data": ["Book your Unicorn Day now.", "Start the survey and get your roadmap.", "Claim your free AI audit today."]},
    {"category": "pain_agitation", "data": ["Wasting $8k/month on brittle Zapier zaps?", "Manual data entry killing team morale?", "Scaling feels impossible with current stack?"]},
    {"category": "methodology_steps", "data": ["Step 1: Discovery → Step 7: Live AI agents running.", "From audit to deployment in under 21 days.", "Our 7-step Unicorn Process is battle-tested."]},
    {"category": "technical_wins", "data": ["Edge-rendered at 98 Lighthouse score.", "Zero third-party dependency after migration."]},
    {"category": "case_study_tease", "data": ["Dallas logistics firm replaced 47 Zaps with one private AI agent.", "Austin fintech saved $187k in year one."]},
    {"category": "pricing_tease", "data": ["Unicorn Day: $4,997 — 8 hours 1:1.", "AI Architecture Audit: Complimentary for qualified leads."]},
    {"category": "local_tie_in", "data": ["Right by the landmark we built the same system for...", "In this market, speed wins."]},
    {"category": "survey_cta", "data": ["👉 Start 90-Second Unicorn Readiness Survey", "Take the survey → Get your roadmap in 5 minutes."]},
    {"category": "final_close", "data": ["Stop guessing. Start building your private AI empire today.", "The next move is yours."]},
]

CONTENT_FRAGMENTS = [
    ("intro_hook", "{b2b_pain_points} If you're still managing 47 Zapier zaps manually, it's time to {grow} with a true {unicorn} who builds {software} that actually prints money while you sleep."),
    ("intro_hook", "In {City}'s competitive tech scene, slow automation is death. {urgency_hooks} Let a {unicorn} rebuild your entire {pipeline}."),
    ("intro_hook", "{social_proof} We don't just code — we architect {revenue} machines that {convert} strangers into enterprise clients."),
    ("intro_hook", "Ready to replace your entire ops team with private AI? {survey_hooks} You've found the {expert}."),
    ("intro_hook", "{b2b_pain_points} If you're ready to {grow} your business with a true {unicorn} who builds {software} that makes money while you sleep, you've found him."),
    ("intro_hook", "Tired of duct-taping your stack? {urgency_hooks} We build systems that scale."),
    ("intro_hook", "Most founders overpay for broken automation. Here's how to {convert} traffic into {revenue} with the right {architecture}."),
    ("intro_hook", "{geo_brags} Whether you're near {Landmark} or scaling across {County}, we deliver {fast}."),
    ("intro_hook", "{pain_agitation} The {expert} solution: private AI and headless architecture."),
    ("intro_hook", "Stop guessing. {survey_hooks} Get your custom {ai} roadmap in 5 minutes."),
    ("hero_section", "## The {City} Unicorn Developer Building Private AI Systems That Replace Entire Departments"),
    ("hero_section", "## Private AI & Headless Architecture for {local} Businesses That Want to 10x Without Hiring"),
    ("hero_section", "# The {expert} Who Builds {software} That Actually Works — Right Here in {City}"),
    ("hero_section", "## From Zapier Hell to Private AI: The {unicorn} Path for {City} Founders"),
    ("hero_section", "# {results} — We Build Revenue Engines for {local} B2B Teams"),
    ("hero_section", "## The Private AI Architect for {City} — Systems That Run While You Sleep"),
    ("hero_section", "# {survey} — 90 Seconds to Your Custom {ai} Roadmap"),
    ("hero_section", "## {expert} {headless} and {zapier} Solutions for {City}"),
    ("problem_agitation", "## Why Most B2B Teams Are Quietly Losing $187k/Year\n\n- Manual workflows\n- Brittle Zapier chains\n- Zero visibility\n- Competitors pulling ahead"),
    ("problem_agitation", "## The Hidden Cost of Duct-Tape Tech Stacks\n\n{pain_agitation}"),
    ("problem_agitation", "## Why 87% of B2B Teams Still Waste 20 Hours/Week on Manual Workflows\n\n{objection_handlers}"),
    ("problem_agitation", "## {b2b_pain_points}\n\nIt doesn't have to be this way."),
    ("problem_agitation", "## Legacy Systems Kill Growth\n\n{urgency_hooks}"),
    ("problem_agitation", "## Integration Hell Is Real\n\n- Third-party dependencies\n- Brittle zaps\n- No control"),
    ("problem_agitation", "## The Pipeline Problem\n\nPipeline drying up? {tech_value_props}"),
    ("problem_agitation", "## Before You Hire Another Dev...\n\n{objection_handlers}"),
    ("methodology", "## Our 7-Step Unicorn Process\n1. Discovery Audit\n2. Private AI Design\n3. Architecture Blueprint\n4. Build & Integrate\n5. Testing\n6. Deploy\n7. Live Revenue Engine"),
    ("methodology", "## {methodology_steps}"),
    ("methodology", "## From Audit to Production in Under 21 Days\n\nStep 1: Deep-dive audit. Step 7: AI agents running."),
    ("methodology", "## The Unicorn Process: {technical_wins}"),
    ("methodology", "## How We Build: Discovery → Design → Deploy"),
    ("methodology", "## 7 Steps to {revenue} Without Hiring"),
    ("methodology", "## Our {architecture} Approach"),
    ("methodology", "## Methodology: {fast} Delivery Guaranteed"),
    ("technical_benefits", "### Headless Edge Delivery\n{technical_wins}"),
    ("technical_benefits", "### Private AI Layer\n{ai} that stays in your stack."),
    ("technical_benefits", "### Zero Third-Party Dependency\n{zapier} built in native code."),
    ("technical_benefits", "### {tech_stack}\nEnterprise-grade, {fast}."),
    ("technical_benefits", "### Scalable {architecture}\n{headless} + {automation}."),
    ("technical_benefits", "### {programmatic} Ready\n1,750+ pages from one template."),
    ("case_study_teaser", "### Austin Fintech → $187k Saved\nReplaced 47 Zaps with one private AI agent in 11 days."),
    ("case_study_teaser", "{case_study_tease}"),
    ("case_study_teaser", "### {results}\n{results_quantified}"),
    ("case_study_teaser", "### Dallas Logistics: 3.4x Pipeline in 47 Days"),
    ("case_study_teaser", "### {social_proof}"),
    ("case_study_teaser", "### Before/After: {revenue} Engine Live"),
    ("geo_bridge", "{geo_brags} Whether you're steps from {Landmark} or scaling across {County}, we build systems that understand {City}."),
    ("geo_bridge", "Right here in {City} near {Landmark} we've built {software} for {local} clients."),
    ("geo_bridge", "{local_tie_in}"),
    ("geo_bridge", "The {City} tech scene demands {fast} execution. We deliver."),
    ("geo_bridge", "{County} enterprises trust us for {headless} and {ai}."),
    ("geo_bridge", "From {Landmark} to {State} startups — we're local."),
    ("geo_bridge", "{local} businesses deserve {expert} {architecture}."),
    ("geo_bridge", "Serving {City} and the greater {County} market."),
    ("social_proof", '> "Chris built our entire AI ops layer in 9 days. Pipeline tripled." — CTO, ScaleFlow'),
    ("social_proof", "{results_quantified}"),
    ("social_proof", "> {social_proof}"),
    ("social_proof", "Trusted by {local} founders for {revenue} engines."),
    ("social_proof", "{case_study_tease}"),
    ("social_proof", "> {geo_brags}"),
    ("results_quantified", "| Metric | Before | After |\n|--------|--------|-------|\n| Pipeline | $42k/mo | $187k/mo |"),
    ("results_quantified", "{results}"),
    ("results_quantified", "{results_quantified}"),
    ("results_quantified", "| Delivery | 60 days | 14 days |\n| Uptime | 92% | 98% |"),
    ("results_quantified", "{technical_wins}"),
    ("results_quantified", "10x pipeline in under 90 days."),
    ("faq_section", "### How fast can you replace Zapier?\nIn most cases we deliver a production-grade replacement {fast} — usually 14–18 days."),
    ("faq_section", "### How long until I see leads?\n{faq_answers}"),
    ("faq_section", "### What's your uniqueness guarantee?\n82% minimum across all {programmatic} pages."),
    ("faq_section", "### Do you work with existing dev teams?\n{objection_handlers}"),
    ("faq_section", "### How does the {survey} work?\n90 seconds. Custom roadmap. No pitch."),
    ("faq_section", "### What's Unicorn Day?\n{pricing_tease}"),
    ("survey_cta_inline", "👉 **Take the 90-Second Unicorn Readiness Survey** — get your custom AI roadmap in 5 minutes. [Start Survey](/survey/unicorn-readiness?source=article)"),
    ("survey_cta_inline", "{survey_cta}"),
    ("survey_cta_inline", "{survey_hooks} [Start Now →](/survey)"),
    ("survey_cta_inline", "Ready for your roadmap? {cta_strong}"),
    ("conclusion", "Stop guessing. Start building. The next move is yours."),
    ("conclusion", "{final_close}"),
    ("conclusion", "The {unicorn} path: {architecture} that {convert}s. {cta_strong}"),
    ("conclusion", "Your {revenue} engine awaits. {cta_strong}"),
    ("final_cta", "## Claim Your Free AI Architecture Survey\n[Start Now →](/survey/ai-blueprint)"),
    ("final_cta", "## {cta_strong}\n[Reserve Unicorn Day](/book)"),
    ("final_cta", "## {survey}\n[Start 90-Second Survey](/survey)"),
    ("final_cta", "## Book Your {audit}\n[Get Audit](/audit)"),
    ("objection_handler", '### "I already have a dev team"\nHere\'s why you still need a {unicorn} for the AI layer.'),
    ("objection_handler", "### {objection_handlers}"),
    ("objection_handler", '### "Too expensive?"\nSee the ROI calculator. {pricing_tease}'),
    ("objection_handler", '### "Not ready for AI?"\nStart with a 2-hour {audit}.'),
    ("pricing_teaser", "### Unicorn Developer Day — $4,997\n8 hours 1:1 with Chris Amaya"),
    ("pricing_teaser", "{pricing_tease}"),
    ("pricing_teaser", "### {survey} — Complimentary\nGet your roadmap in 5 minutes."),
    ("pricing_teaser", "### {audit} — Free for qualified leads"),
]

HEADLINES = [
    ("h1", "The Unicorn Developer Who Builds {Private AI Systems|Custom SaaS} That {10x|Replace} Your Entire Operations in {City}"),
    ("h1", "Private AI Systems & Zapier Replacements Built {fast} in 14 Days for {City} Businesses"),
    ("h1", "The {City} {Unicorn Developer|One-Stop Architect} Building {software} That Runs While You Sleep"),
    ("h1", "{Ready to|Want to|Need to} {build|launch|scale|automate} Your {Custom SaaS|Private AI System|Unicorn App} {in|for} {City}?"),
    ("h1", "The {expert} Who Delivers {revenue} Engines for {local} B2B Teams"),
    ("h1", "{City} {headless} & {zapier} — Built by a {unicorn}"),
    ("h1", "From Zapier to Private AI: The {City} Unicorn Path"),
    ("h1", "{survey} — 90 Seconds to Your {ai} Roadmap in {City}"),
    ("h2", "Why Most B2B Teams Lose $187k/Year on Broken Automation"),
    ("h2", "The Problem: Manual Workflows + Brittle Zaps"),
    ("h2", "The Solution: Private AI + Headless Architecture"),
    ("h2", "Our 7-Step Unicorn Process"),
    ("h2", "Technical Benefits: {tech_stack}"),
    ("h2", "Results: {results}"),
    ("h2", "Case Studies from {City} and Beyond"),
    ("h2", "Serving {City} Near {Landmark}"),
    ("h2", "What {local} Founders Say"),
    ("h2", "FAQ: {survey}, Unicorn Day, and More"),
    ("h2", "{cta_strong}"),
    ("h3", "Headless Edge Delivery"),
    ("h3", "Private AI Layer"),
    ("h3", "Zero Third-Party Dependency"),
    ("h3", "Scalable {architecture}"),
    ("h3", "{programmatic} at Scale"),
    ("h3", "How {fast} Can You Deliver?"),
    ("h3", "What's Unicorn Day?"),
    ("h3", "Do You Work With Existing Teams?"),
]

OFFER_BLOCKS = [
    {"block_type": "unicorn_readiness_survey", "data": {"headline": "Free 90-Second Unicorn Readiness Survey", "button_text": "Start Survey Now", "form_fields": ["Name", "Email", "Company", "Biggest Bottleneck"]}},
    {"block_type": "ai_architecture_audit", "data": {"headline": "Claim Your Private AI Architecture Audit", "button_text": "Get Audit", "form_fields": ["URL", "Email"]}},
    {"block_type": "zapier_replacement_scorecard", "data": {"headline": "Zapier Replacement Scorecard (Instant)", "button_text": "Score My Workflows", "form_fields": ["Email"]}},
    {"block_type": "unicorn_day", "data": {"headline": "Book Your Private Unicorn Developer Day", "button_text": "Reserve My Day", "form_fields": ["Name", "Email", "Business Goal"]}},
    {"block_type": "technical_strategy_session", "data": {"headline": "Technical Strategy Session — No Pitch", "button_text": "Book Session", "form_fields": ["Name", "Email"]}},
    {"block_type": "headless_readiness_check", "data": {"headline": "Headless Readiness Check", "button_text": "Get Check", "form_fields": ["Email", "Current Stack"]}},
    {"block_type": "ai_blueprint", "data": {"headline": "Free AI Blueprint", "button_text": "Claim Blueprint", "form_fields": ["Email"]}},
    {"block_type": "cta", "data": {"headline": "Get a Free Quote Today", "button_text": "Get Free Quote", "form_action": "/api/submit-lead"}},
    {"block_type": "cta", "data": {"headline": "Need Help? Contact Us Now", "button_text": "Contact Us", "form_action": "/api/submit-lead"}},
    {"block_type": "strategy_call", "data": {"headline": "15-Min Strategy Call", "button_text": "Book Call", "form_fields": ["Name", "Email", "Phone"]}},
    {"block_type": "audit", "data": {"headline": "2-Hour Technical Audit", "button_text": "Request Audit", "form_fields": ["Email", "Website"]}},
    {"block_type": "demo", "data": {"headline": "Zapier Replacement Demo", "button_text": "See Demo", "form_fields": ["Email"]}},
    {"block_type": "roadmap", "data": {"headline": "Custom AI Roadmap", "button_text": "Get Roadmap", "form_fields": ["Email"]}},
    {"block_type": "survey_cta", "data": {"headline": "90-Second Unicorn Survey", "button_text": "Start Survey", "form_fields": ["Email"]}},
    {"block_type": "unicorn_day_teaser", "data": {"headline": "Unicorn Day — $4,997", "button_text": "Reserve", "form_fields": ["Name", "Email"]}},
    {"block_type": "free_audit", "data": {"headline": "Free Architecture Audit", "button_text": "Claim Audit", "form_fields": ["Email"]}},
    {"block_type": "ai_assessment", "data": {"headline": "AI Readiness Assessment", "button_text": "Get Assessment", "form_fields": ["Email", "Company"]}},
    {"block_type": "pipeline_build", "data": {"headline": "Revenue Pipeline Build", "button_text": "Learn More", "form_fields": ["Name", "Email"]}},
]


def _geo_for_slug(slug: str) -> dict:
    """Generate geo_intelligence data for a location slug."""
    parts = slug.rsplit("-", 1)
    city = (parts[0] or "Austin").replace("-", " ").title()
    state = (parts[1] if len(parts) > 1 else "TX").upper()
    counties = {
        "austin-tx": "Travis", "dallas-tx": "Dallas", "houston-tx": "Harris",
        "san-antonio-tx": "Bexar", "miami-fl": "Miami-Dade", "atlanta-ga": "Fulton",
        "phoenix-az": "Maricopa", "denver-co": "Denver", "chicago-il": "Cook",
        "seattle-wa": "King", "los-angeles-ca": "Los Angeles", "san-francisco-ca": "San Francisco",
    }
    county = counties.get(slug, (city + " County") if state else "County")
    landmarks = {
        "austin-tx": "Texas State Capitol", "dallas-tx": "Reunion Tower",
        "houston-tx": "Space Center Houston", "miami-fl": "Art Deco Historic District",
        "chicago-il": "Millennium Park", "seattle-wa": "Space Needle",
        "san-francisco-ca": "Golden Gate Bridge", "denver-co": "Red Rocks",
    }
    landmark = landmarks.get(slug, f"{city} Downtown")
    return {
        "city": city,
        "state": state,
        "county": county,
        "landmark": landmark,
        "tech_scene_description": f"Growing tech ecosystem in {city}, {state}",
        "notable_companies": "Scale-ups and enterprises",
        "local_pain_points": "Manual workflows, legacy systems, scaling challenges",
    }
